### ISSUE TITLE
Firth & Wilson

### ISSUE THREAD

**Issue by gsf** [natlownes/ampersand-and-and#8]
Great list!

**Comment by natlownes** [comment]
ha, thanks @gsf 

the completely arbitrary rules for this stupid list are that proper nouns don't count - gotta be regular boring nouns.  or something wildly ridiculous, like if someone opens say "Sultry and Sullen", that might change the game

**Comment by gsf** [comment]
Rules! I didn't realize. Also that's a good name for a coffee shop.
